### PR TITLE
Modified the Student form

### PR DESCRIPTION
**Pull request by Masagazi-Ruth**
Modified the Student form

### CODE REVIEW

**Review by NANTONGO-JOSELYN — COMMENTED** [review]
No conflicts

**Comment by NANTONGO-JOSELYN** [comment]
No conflicts

**Comment by NANTONGO-JOSELYN** [comment]
no conflict

**Review by NANTONGO-JOSELYN — COMMENTED** [review]
no conflicts

**Review by Masagazi-Ruth — COMMENTED** [review]
Student form modification

**Review by NANTONGO-JOSELYN — APPROVED** [review]
fine

**Pull request merged**
